CREATE TABLE `secret_end_report` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `pool_key` varchar(50) DEFAULT '' COMMENT '号码池key',
  `sub_id` bigint(20) DEFAULT '0' COMMENT '绑定关系ID',
  `download_url` varchar(255) DEFAULT NULL COMMENT '录音下载URL',
  `ring_record_url` varchar(255) DEFAULT NULL COMMENT '放音录音URL',
  `call_id` varchar(100) NOT NULL DEFAULT '' COMMENT '唯一标识一通通话记录的ID',
  `phone_no` varchar(50) DEFAULT '' COMMENT 'A号码',
  `secret_no` varchar(50) DEFAULT '' COMMENT '隐私号码X',
  `peer_no` varchar(50) DEFAULT '' COMMENT 'B或者N号码',
  `called_display_no` varchar(50) DEFAULT '' COMMENT '被叫显号',
  `call_type` int(2) DEFAULT '0' COMMENT '呼叫类型 0：主叫（phone_no打给peer_no）1：被叫（peer_no打给phone_no）4：呼叫拦截',
  `call_time` datetime DEFAULT NULL COMMENT '主叫拨打时间',
  `start_time` datetime DEFAULT NULL COMMENT '被叫接听时间（通话计费开始时间）。如未接通，则等于release_time的时间。短信话单时，此值传短信接收时间。',
  `call_out_time` datetime DEFAULT NULL COMMENT '呼叫被叫侧发起的时间。如未发起，则等于call_time的时间；短信话单时，此值传短信接收时间。',
  `ring_time` datetime DEFAULT NULL COMMENT '被叫响铃时间。如没有响铃时间，则等于call_out_time的时间。短信话单时，此值传短信接收时间。',
  `free_ring_time` datetime DEFAULT NULL COMMENT '被叫空闲振铃时间，free_ring_time大于call_out_time表示被叫真实发生了振铃事件。free_ring_time和call_out_time相等表示未振铃。如获取不到，则等于ring_time的时间。',
  `release_time` datetime DEFAULT NULL COMMENT '通话释放时间（通话计费结束时间）；短信话单时，此值传短信接收时间。release_time和start_time之差表示通话时长， 如果结果为0，说明呼叫未接通。',
  `sms_number` int(10) DEFAULT '0' COMMENT '短信长度',
  `release_dir` int(1) DEFAULT '3' COMMENT '通话释放方向 0：平台释放 1：主叫挂断 2：被叫挂断',
  `out_id` varchar(50) DEFAULT '' COMMENT '外部业务ID',
  `unconnected_cause` int(1) DEFAULT '0' COMMENT '未接通通话的原因归类 0：正常通话 1：黑名单拦截 2：无绑定关系 3：呼叫限制 4：其他',
  `release_cause` int(3) DEFAULT '0' COMMENT '释放原因',
  `release_cause_describe` varchar(255) DEFAULT '' COMMENT '释放原因描述',
  `control_msg` varchar(50) DEFAULT 'NO_SUBS_EXIST' COMMENT '无绑定关系时返回NO_SUBS_EXIST',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_call_id` (`call_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='呼叫结束时话单回执消息SecretReport';